

export function Delivery() {
    return (
        <>
        <div className="delivery">
           
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
           <h2>Component</h2>
        </div>  
        </>
    );
}